// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: body_metrics.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createBodyMetric = `-- name: CreateBodyMetric :one
INSERT INTO body_metrics (
    weight_kg, body_fat_pct, muscle_pct, visceral_fat, recorded_at, note
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, weight_kg, body_fat_pct, muscle_pct, visceral_fat, recorded_at, note, created_at, updated_at
`

type CreateBodyMetricParams struct {
	WeightKg    sql.NullString `json:"weight_kg"`
	BodyFatPct  sql.NullString `json:"body_fat_pct"`
	MusclePct   sql.NullString `json:"muscle_pct"`
	VisceralFat sql.NullInt16  `json:"visceral_fat"`
	RecordedAt  time.Time      `json:"recorded_at"`
	Note        sql.NullString `json:"note"`
}

func (q *Queries) CreateBodyMetric(ctx context.Context, arg *CreateBodyMetricParams) (BodyMetric, error) {
	row := q.db.QueryRowContext(ctx, createBodyMetric,
		arg.WeightKg,
		arg.BodyFatPct,
		arg.MusclePct,
		arg.VisceralFat,
		arg.RecordedAt,
		arg.Note,
	)
	var i BodyMetric
	err := row.Scan(
		&i.ID,
		&i.WeightKg,
		&i.BodyFatPct,
		&i.MusclePct,
		&i.VisceralFat,
		&i.RecordedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBodyMetric = `-- name: DeleteBodyMetric :exec
DELETE FROM body_metrics WHERE id = $1
`

func (q *Queries) DeleteBodyMetric(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBodyMetric, id)
	return err
}

const getBodyMetric = `-- name: GetBodyMetric :one
SELECT id, weight_kg, body_fat_pct, muscle_pct, visceral_fat, recorded_at, note, created_at, updated_at FROM body_metrics WHERE id = $1
`

func (q *Queries) GetBodyMetric(ctx context.Context, id uuid.UUID) (BodyMetric, error) {
	row := q.db.QueryRowContext(ctx, getBodyMetric, id)
	var i BodyMetric
	err := row.Scan(
		&i.ID,
		&i.WeightKg,
		&i.BodyFatPct,
		&i.MusclePct,
		&i.VisceralFat,
		&i.RecordedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBodyMetrics = `-- name: ListBodyMetrics :many
SELECT id, weight_kg, body_fat_pct, muscle_pct, visceral_fat, recorded_at, note, created_at, updated_at FROM body_metrics
WHERE
    ($1::DATE IS NULL OR recorded_at::DATE >= $1::DATE)
    AND ($2::DATE IS NULL OR recorded_at::DATE <= $2::DATE)
ORDER BY recorded_at DESC
LIMIT $3
`

type ListBodyMetricsParams struct {
	From  sql.NullTime `json:"from"`
	To    sql.NullTime `json:"to"`
	Limit int32        `json:"limit"`
}

func (q *Queries) ListBodyMetrics(ctx context.Context, arg *ListBodyMetricsParams) ([]BodyMetric, error) {
	rows, err := q.db.QueryContext(ctx, listBodyMetrics, arg.From, arg.To, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BodyMetric
	for rows.Next() {
		var i BodyMetric
		if err := rows.Scan(
			&i.ID,
			&i.WeightKg,
			&i.BodyFatPct,
			&i.MusclePct,
			&i.VisceralFat,
			&i.RecordedAt,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBodyMetric = `-- name: UpdateBodyMetric :one
UPDATE body_metrics
SET
    weight_kg    = COALESCE($1, weight_kg),
    body_fat_pct = COALESCE($2, body_fat_pct),
    muscle_pct   = COALESCE($3, muscle_pct),
    visceral_fat = COALESCE($4, visceral_fat),
    note         = COALESCE($5, note),
    updated_at   = NOW()
WHERE id = $6
RETURNING id, weight_kg, body_fat_pct, muscle_pct, visceral_fat, recorded_at, note, created_at, updated_at
`

type UpdateBodyMetricParams struct {
	WeightKg    sql.NullString `json:"weight_kg"`
	BodyFatPct  sql.NullString `json:"body_fat_pct"`
	MusclePct   sql.NullString `json:"muscle_pct"`
	VisceralFat sql.NullInt16  `json:"visceral_fat"`
	Note        sql.NullString `json:"note"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateBodyMetric(ctx context.Context, arg *UpdateBodyMetricParams) (BodyMetric, error) {
	row := q.db.QueryRowContext(ctx, updateBodyMetric,
		arg.WeightKg,
		arg.BodyFatPct,
		arg.MusclePct,
		arg.VisceralFat,
		arg.Note,
		arg.ID,
	)
	var i BodyMetric
	err := row.Scan(
		&i.ID,
		&i.WeightKg,
		&i.BodyFatPct,
		&i.MusclePct,
		&i.VisceralFat,
		&i.RecordedAt,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
