// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_activities.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDailyActivity = `-- name: CreateDailyActivity :one
INSERT INTO daily_activities (
    activity_date, steps, commute_mode, commute_minutes, note
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at
`

type CreateDailyActivityParams struct {
	ActivityDate   time.Time       `json:"activity_date"`
	Steps          sql.NullInt32   `json:"steps"`
	CommuteMode    NullCommuteMode `json:"commute_mode"`
	CommuteMinutes sql.NullInt32   `json:"commute_minutes"`
	Note           sql.NullString  `json:"note"`
}

func (q *Queries) CreateDailyActivity(ctx context.Context, arg *CreateDailyActivityParams) (DailyActivity, error) {
	row := q.db.QueryRowContext(ctx, createDailyActivity,
		arg.ActivityDate,
		arg.Steps,
		arg.CommuteMode,
		arg.CommuteMinutes,
		arg.Note,
	)
	var i DailyActivity
	err := row.Scan(
		&i.ID,
		&i.ActivityDate,
		&i.Steps,
		&i.CommuteMode,
		&i.CommuteMinutes,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDailyActivity = `-- name: DeleteDailyActivity :exec
DELETE FROM daily_activities WHERE id = $1
`

func (q *Queries) DeleteDailyActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDailyActivity, id)
	return err
}

const getDailyActivity = `-- name: GetDailyActivity :one
SELECT id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at FROM daily_activities WHERE id = $1
`

func (q *Queries) GetDailyActivity(ctx context.Context, id uuid.UUID) (DailyActivity, error) {
	row := q.db.QueryRowContext(ctx, getDailyActivity, id)
	var i DailyActivity
	err := row.Scan(
		&i.ID,
		&i.ActivityDate,
		&i.Steps,
		&i.CommuteMode,
		&i.CommuteMinutes,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyActivityByDate = `-- name: GetDailyActivityByDate :one
SELECT id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at FROM daily_activities WHERE activity_date = $1
`

func (q *Queries) GetDailyActivityByDate(ctx context.Context, activityDate time.Time) (DailyActivity, error) {
	row := q.db.QueryRowContext(ctx, getDailyActivityByDate, activityDate)
	var i DailyActivity
	err := row.Scan(
		&i.ID,
		&i.ActivityDate,
		&i.Steps,
		&i.CommuteMode,
		&i.CommuteMinutes,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDailyActivities = `-- name: ListDailyActivities :many
SELECT id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at FROM daily_activities
WHERE
    ($1::DATE IS NULL OR activity_date >= $1::DATE)
    AND ($2::DATE IS NULL OR activity_date <= $2::DATE)
ORDER BY activity_date DESC
LIMIT $3
`

type ListDailyActivitiesParams struct {
	From  sql.NullTime `json:"from"`
	To    sql.NullTime `json:"to"`
	Limit int32        `json:"limit"`
}

func (q *Queries) ListDailyActivities(ctx context.Context, arg *ListDailyActivitiesParams) ([]DailyActivity, error) {
	rows, err := q.db.QueryContext(ctx, listDailyActivities, arg.From, arg.To, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyActivity
	for rows.Next() {
		var i DailyActivity
		if err := rows.Scan(
			&i.ID,
			&i.ActivityDate,
			&i.Steps,
			&i.CommuteMode,
			&i.CommuteMinutes,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDailyActivity = `-- name: UpdateDailyActivity :one
UPDATE daily_activities
SET
    steps           = COALESCE($1, steps),
    commute_mode    = COALESCE($2, commute_mode),
    commute_minutes = COALESCE($3, commute_minutes),
    note            = COALESCE($4, note),
    updated_at      = NOW()
WHERE id = $5
RETURNING id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at
`

type UpdateDailyActivityParams struct {
	Steps          sql.NullInt32   `json:"steps"`
	CommuteMode    NullCommuteMode `json:"commute_mode"`
	CommuteMinutes sql.NullInt32   `json:"commute_minutes"`
	Note           sql.NullString  `json:"note"`
	ID             uuid.UUID       `json:"id"`
}

func (q *Queries) UpdateDailyActivity(ctx context.Context, arg *UpdateDailyActivityParams) (DailyActivity, error) {
	row := q.db.QueryRowContext(ctx, updateDailyActivity,
		arg.Steps,
		arg.CommuteMode,
		arg.CommuteMinutes,
		arg.Note,
		arg.ID,
	)
	var i DailyActivity
	err := row.Scan(
		&i.ID,
		&i.ActivityDate,
		&i.Steps,
		&i.CommuteMode,
		&i.CommuteMinutes,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
