// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_activities.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDailyActivity = `-- name: CreateDailyActivity :one
INSERT INTO daily_activities (
    user_id, activity_date, steps, commute_mode, commute_minutes, note
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at
`

type CreateDailyActivityParams struct {
	UserID         uuid.UUID       `json:"user_id"`
	ActivityDate   time.Time       `json:"activity_date"`
	Steps          sql.NullInt32   `json:"steps"`
	CommuteMode    NullCommuteMode `json:"commute_mode"`
	CommuteMinutes sql.NullInt32   `json:"commute_minutes"`
	Note           sql.NullString  `json:"note"`
}

func (q *Queries) CreateDailyActivity(ctx context.Context, arg *CreateDailyActivityParams) (DailyActivity, error) {
	row := q.db.QueryRowContext(ctx, createDailyActivity,
		arg.UserID,
		arg.ActivityDate,
		arg.Steps,
		arg.CommuteMode,
		arg.CommuteMinutes,
		arg.Note,
	)
	var i DailyActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityDate,
		&i.Steps,
		&i.CommuteMode,
		&i.CommuteMinutes,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDailyActivity = `-- name: DeleteDailyActivity :exec
DELETE FROM daily_activities WHERE id = $1 AND user_id = $2
`

type DeleteDailyActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDailyActivity(ctx context.Context, arg *DeleteDailyActivityParams) error {
	_, err := q.db.ExecContext(ctx, deleteDailyActivity, arg.ID, arg.UserID)
	return err
}

const getDailyActivity = `-- name: GetDailyActivity :one
SELECT id, user_id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at FROM daily_activities WHERE id = $1 AND user_id = $2
`

type GetDailyActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDailyActivity(ctx context.Context, arg *GetDailyActivityParams) (DailyActivity, error) {
	row := q.db.QueryRowContext(ctx, getDailyActivity, arg.ID, arg.UserID)
	var i DailyActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityDate,
		&i.Steps,
		&i.CommuteMode,
		&i.CommuteMinutes,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDailyActivities = `-- name: ListDailyActivities :many
SELECT id, user_id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at FROM daily_activities
WHERE
    user_id = $1
    AND ($2::DATE IS NULL OR activity_date >= $2::DATE)
    AND ($3::DATE IS NULL OR activity_date <= $3::DATE)
ORDER BY activity_date DESC
LIMIT $4
`

type ListDailyActivitiesParams struct {
	UserID uuid.UUID    `json:"user_id"`
	From   sql.NullTime `json:"from"`
	To     sql.NullTime `json:"to"`
	Limit  int32        `json:"limit"`
}

func (q *Queries) ListDailyActivities(ctx context.Context, arg *ListDailyActivitiesParams) ([]DailyActivity, error) {
	rows, err := q.db.QueryContext(ctx, listDailyActivities,
		arg.UserID,
		arg.From,
		arg.To,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyActivity
	for rows.Next() {
		var i DailyActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityDate,
			&i.Steps,
			&i.CommuteMode,
			&i.CommuteMinutes,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDailyActivity = `-- name: UpdateDailyActivity :one
UPDATE daily_activities
SET
    steps           = COALESCE($1, steps),
    commute_mode    = COALESCE($2, commute_mode),
    commute_minutes = COALESCE($3, commute_minutes),
    note            = COALESCE($4, note),
    updated_at      = NOW()
WHERE id = $5 AND user_id = $6
RETURNING id, user_id, activity_date, steps, commute_mode, commute_minutes, note, created_at, updated_at
`

type UpdateDailyActivityParams struct {
	Steps          sql.NullInt32   `json:"steps"`
	CommuteMode    NullCommuteMode `json:"commute_mode"`
	CommuteMinutes sql.NullInt32   `json:"commute_minutes"`
	Note           sql.NullString  `json:"note"`
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
}

func (q *Queries) UpdateDailyActivity(ctx context.Context, arg *UpdateDailyActivityParams) (DailyActivity, error) {
	row := q.db.QueryRowContext(ctx, updateDailyActivity,
		arg.Steps,
		arg.CommuteMode,
		arg.CommuteMinutes,
		arg.Note,
		arg.ID,
		arg.UserID,
	)
	var i DailyActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityDate,
		&i.Steps,
		&i.CommuteMode,
		&i.CommuteMinutes,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
