// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type CommuteMode string

const (
	CommuteModeScooter CommuteMode = "scooter"
	CommuteModeTrain   CommuteMode = "train"
	CommuteModeWalk    CommuteMode = "walk"
	CommuteModeOther   CommuteMode = "other"
)

func (e *CommuteMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommuteMode(s)
	case string:
		*e = CommuteMode(s)
	default:
		return fmt.Errorf("unsupported scan type for CommuteMode: %T", src)
	}
	return nil
}

type NullCommuteMode struct {
	CommuteMode CommuteMode `json:"commute_mode"`
	Valid       bool        `json:"valid"` // Valid is true if CommuteMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommuteMode) Scan(value interface{}) error {
	if value == nil {
		ns.CommuteMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommuteMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommuteMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommuteMode), nil
}

type BodyMetric struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	WeightKg    sql.NullString `json:"weight_kg"`
	BodyFatPct  sql.NullString `json:"body_fat_pct"`
	MusclePct   sql.NullString `json:"muscle_pct"`
	VisceralFat sql.NullInt16  `json:"visceral_fat"`
	RecordedAt  time.Time      `json:"recorded_at"`
	Note        sql.NullString `json:"note"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type DailyActivity struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	ActivityDate   time.Time       `json:"activity_date"`
	Steps          sql.NullInt32   `json:"steps"`
	CommuteMode    NullCommuteMode `json:"commute_mode"`
	CommuteMinutes sql.NullInt32   `json:"commute_minutes"`
	Note           sql.NullString  `json:"note"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
	CreatedAt time.Time `json:"created_at"`
}

type SleepLog struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	SleepAt      time.Time      `json:"sleep_at"`
	WakeAt       time.Time      `json:"wake_at"`
	DurationMin  sql.NullInt32  `json:"duration_min"`
	AbnormalWake bool           `json:"abnormal_wake"`
	Quality      sql.NullInt16  `json:"quality"`
	Note         sql.NullString `json:"note"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	GoogleID    string         `json:"google_id"`
	Email       string         `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	CreatedAt   time.Time      `json:"created_at"`
	LastLoginAt time.Time      `json:"last_login_at"`
}
