// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sleep_logs.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createSleepLog = `-- name: CreateSleepLog :one
INSERT INTO sleep_logs (
    sleep_at, wake_at, quality, note
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, sleep_at, wake_at, duration_min, abnormal_wake, quality, note, created_at, updated_at
`

type CreateSleepLogParams struct {
	SleepAt time.Time      `json:"sleep_at"`
	WakeAt  time.Time      `json:"wake_at"`
	Quality sql.NullInt16  `json:"quality"`
	Note    sql.NullString `json:"note"`
}

func (q *Queries) CreateSleepLog(ctx context.Context, arg *CreateSleepLogParams) (SleepLog, error) {
	row := q.db.QueryRowContext(ctx, createSleepLog,
		arg.SleepAt,
		arg.WakeAt,
		arg.Quality,
		arg.Note,
	)
	var i SleepLog
	err := row.Scan(
		&i.ID,
		&i.SleepAt,
		&i.WakeAt,
		&i.DurationMin,
		&i.AbnormalWake,
		&i.Quality,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSleepLog = `-- name: DeleteSleepLog :exec
DELETE FROM sleep_logs WHERE id = $1
`

func (q *Queries) DeleteSleepLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSleepLog, id)
	return err
}

const getSleepLog = `-- name: GetSleepLog :one
SELECT id, sleep_at, wake_at, duration_min, abnormal_wake, quality, note, created_at, updated_at FROM sleep_logs WHERE id = $1
`

func (q *Queries) GetSleepLog(ctx context.Context, id uuid.UUID) (SleepLog, error) {
	row := q.db.QueryRowContext(ctx, getSleepLog, id)
	var i SleepLog
	err := row.Scan(
		&i.ID,
		&i.SleepAt,
		&i.WakeAt,
		&i.DurationMin,
		&i.AbnormalWake,
		&i.Quality,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSleepLogs = `-- name: ListSleepLogs :many
SELECT id, sleep_at, wake_at, duration_min, abnormal_wake, quality, note, created_at, updated_at FROM sleep_logs
WHERE
    -- Filter by wake_at Taipei date (user thinks of sleep by the morning they woke up)
    ($1::DATE IS NULL OR (wake_at AT TIME ZONE 'Asia/Taipei')::DATE >= $1::DATE)
    AND ($2::DATE IS NULL OR (wake_at AT TIME ZONE 'Asia/Taipei')::DATE <= $2::DATE)
    AND ($3::BOOLEAN IS NULL OR ($3 = FALSE) OR abnormal_wake = TRUE)
ORDER BY wake_at DESC
LIMIT $4
`

type ListSleepLogsParams struct {
	Column1 time.Time `json:"column_1"`
	Column2 time.Time `json:"column_2"`
	Column3 bool      `json:"column_3"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListSleepLogs(ctx context.Context, arg *ListSleepLogsParams) ([]SleepLog, error) {
	rows, err := q.db.QueryContext(ctx, listSleepLogs,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SleepLog
	for rows.Next() {
		var i SleepLog
		if err := rows.Scan(
			&i.ID,
			&i.SleepAt,
			&i.WakeAt,
			&i.DurationMin,
			&i.AbnormalWake,
			&i.Quality,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSleepLog = `-- name: UpdateSleepLog :one
UPDATE sleep_logs
SET
    sleep_at   = COALESCE($1, sleep_at),
    wake_at    = COALESCE($2, wake_at),
    quality    = COALESCE($3, quality),
    note       = COALESCE($4, note),
    updated_at = NOW()
WHERE id = $5
RETURNING id, sleep_at, wake_at, duration_min, abnormal_wake, quality, note, created_at, updated_at
`

type UpdateSleepLogParams struct {
	SleepAt sql.NullTime   `json:"sleep_at"`
	WakeAt  sql.NullTime   `json:"wake_at"`
	Quality sql.NullInt16  `json:"quality"`
	Note    sql.NullString `json:"note"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateSleepLog(ctx context.Context, arg *UpdateSleepLogParams) (SleepLog, error) {
	row := q.db.QueryRowContext(ctx, updateSleepLog,
		arg.SleepAt,
		arg.WakeAt,
		arg.Quality,
		arg.Note,
		arg.ID,
	)
	var i SleepLog
	err := row.Scan(
		&i.ID,
		&i.SleepAt,
		&i.WakeAt,
		&i.DurationMin,
		&i.AbnormalWake,
		&i.Quality,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
