// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, google_id, email, display_name, avatar_url, created_at, last_login_at FROM users WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_id, email, display_name, avatar_url, created_at, last_login_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (google_id, email, display_name, avatar_url, last_login_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (google_id) DO UPDATE SET
    email         = EXCLUDED.email,
    display_name  = EXCLUDED.display_name,
    avatar_url    = EXCLUDED.avatar_url,
    last_login_at = NOW()
RETURNING id, google_id, email, display_name, avatar_url, created_at, last_login_at
`

type UpsertUserParams struct {
	GoogleID    string         `json:"google_id"`
	Email       string         `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg *UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser,
		arg.GoogleID,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
